# Generated by Django 5.1.3 on 2024-11-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usermodel_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavemodel',
            old_name='want_leave_date',
            new_name='end_leave_date',
        ),
        migrations.AddField(
            model_name='leavemodel',
            name='start_leave_date',
            field=models.CharField(default='01-01-2001', max_length=10),
            preserve_default=False,
        ),
    ]
