# Generated by Django 5.1.3 on 2024-11-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_want_leave_date_leavemodel_end_leave_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemodel',
            name='end_leave_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
